### Machine Learning Tutorial Python - 3: Linear Regression Multiple Variables

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

#### Data Preprocessing: Fill NA values with median value of a column

In [3]:
median_bedrooms = df.bedrooms.median()

In [4]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'), df.price)

LinearRegression()

In [6]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [7]:
reg.intercept_

221323.00186540396

#### Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [8]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [9]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

#### Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [10]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

### Exercise
In exercise folder (same level as this notebook on github) there is `hiring.csv`. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates:
* 2 yr experience, 9 test score, 6 interview score
* 12 yr experience, 10 test score, 10 interview score

In [11]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [12]:
from word2number import w2n
df.experience = df.experience.fillna("zero")
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [13]:
import math
median_score = math.floor(df['test_score(out of 10)'].mean())
df['test_score(out of 10)'].fillna(median_score, inplace=True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [14]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary($)', axis='columns'),df['salary($)'])

LinearRegression()

In [15]:
reg.predict([[2, 9, 6]])

array([53713.86677124])

In [16]:
reg.predict([[12,10,10]])

array([93747.79628651])